- _redirects
Added redirects for 
`/` `/team` `/events` `/hacktoberfest`
> Created  _redirects File

- public/index.html
i hope i did things right this time, thanks for help
> changes made to index.html

- public/index.html
- src/components/teamCard/index.jsx
- src/components/teamCard/style.module.css
- src/pages/team.jsx
I've implemented the template
#12 #3 
@Souvikns @imabp @JoshuaPoddoku
> Add Team Page

- src/components/sections/landing_bottom.js
- src/components/sections/landing_middle.js
- src/components/teamCard/index.jsx
- src/pages/team.jsx
Removed the hardcoded data in the team component and connected airtable API data. 
closes #57
> added airtable data with team cards

- README.md
Created a readme file for react.
> Readme for react

- package-lock.json
- src/components/project/holder.jsx
> created project card component

- src/App.js
- src/pages/projects.jsx
> added projects page on /projects route

- README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Updating Development

- CONTRIBUTING.md
> Fixed git fetch --all --prune comment

- CONTRIBUTING.md
> Remote link fixed

- src/components/sections/landing_top.js
Decrease padding from the hero section of the homepage #105
> decrease padding from the hero section

- src/projectStructure
By adding a projectStructure.md file inside the src directory, I have added documentation about the folder's structure and hierarchy.
Fixes #114 
No need for tests
> Adding projectStructure file for src folder

- src/components/teamCard/teamLifecycle/index.jsx
Fixed the typo error
Fixes #121  (issue)
Spelling change
> fixed typo

- src/components/project/holder.jsx
I change the width of box to set it with smaller devices
Fixes # (issue)
#115 
**Before**
**After**
> Overflow in projects section in smaller devices (Solved) issue #155

- src/components/sections/landing_bottom.js
- src/components/sections/landing_middle.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Just fixed a few typos as mentioned in the issue [#126 ](https://github.com/Ninja-Developers/Tech_Phantoms_website/issues/126)
Fixes issue #126 
- [  ] Bug fix (non-breaking change which fixes an issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**As this was a Typo fix it will not break any part of the code** 
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
- [  ] My code follows the style guidelines of this project
- …
> Fixed typos in development website page

- projectStructure.md
Added further description of project structure
Fixes #114 
No testing required
> feature-project-structure-documentation

- src/components/sections/landing_bottom.js
- src/components/sections/landing_middle.js
Modified the content in the landing page.
> Modified content in landing page

- src/components/project/holder.jsx
- src/components/project/index.jsx
- src/pages/projects.jsx
Fixes # (issue)
#131
Change Project Section for better look
**Now Project Section**
- [ _/ ] New feature (non-breaking change which adds functionality)
> Revamp Projects Page Issue PR

- src/components/teamCard/teamLifecycle/index.jsx
Correct team page spelling and grammar mistakes
> Correct team page spelling and grammar mistakes

- package-lock.json
- src/index.css
Added a Tomato coloured custom scrollbar to the page. 
Fixes # (issue)
Closes #72
> Custom scroll bar

- src/components/project/badge.jsx
- src/components/project/holder.jsx
- src/components/project/index.jsx
Converted from chakra-UI to Material-UI. 
Fixes #164
> converted projects holder from chakra to material-ui

- src/components/PageNotFound/index.jsx
Now 404 page is in material ui.
Fixes #164 
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules
> Changed 404page to material ui

- README.md
- Removed open urls
- Centre aligned the title
> Prettified README.md

- src/components/teamCard/holder.jsx
- src/components/teamCard/style.module.css
Team page card now does not have a dependency on chakra ui. Now it depends on material ui. I have added a little up down animation on profile image also.
Fixes #164 
Screenshots : 
The Card now looks like this :
Please also see that now the **background color of home page is changed** in my development environment. I don't know why, in chrome it is changed but in mozilla it is fine.
> Changed team page card to material-ui

- src/App.js
- src/components/navbar/navbar.jsx
- src/pages/Project/index.jsx
- src/pages/event/index.jsx
- src/pages/home/index.jsx
- src/pages/home/sections/landing_top.js
- src/pages/team/index.jsx
> Updated Navbar and Props

- src/pages/team/components/holder/holder.jsx
- src/pages/team/sections/coremembers/index.jsx
- src/pages/team/sections/ourstory/creators/index.jsx
- src/pages/team/sections/ourstory/index.jsx
- src/theme.js
#205 
Fixing Holder with New Design
> Updated Holder

- src/pages/LandingPage/components/LandingContent.jsx
- src/pages/LandingPage/components/SpecialBanner.jsx
- src/routes.js
Created links in routes.js for discord, opencollective and apihacks.
#274
> new routes

- src/pages/LandingPage/LandingPage.js
- src/pages/LandingPage/components/LandingContent.jsx
- src/pages/LandingPage/components/SpecialBanner.jsx
@imabp Made UI Changes to the website
> BugFix: made the UI Changes to the Landing Page

- src/pages/LandingPage/components/Announcements.jsx
Announcements Functionality complete
@imabp
> Announcements Complete

- README.md
- Fix banner link in the `README.md` file.
> fix: banner link in the `README.md` file

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Fix the wrong labels in the issue templates.
> fix: wrong labels in the issue templates

- README.md
- Fix the wrong link.
- Improve wording
- Fix minor typos.
> fix: wrong link, improve wording, and typos

- README.md
- package.json
- Update links to point to the new website domain.
> fix: Update links to point to the new website domain

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/other.yml
> fix: Add missing templates

- index.html
> feat: Improve SEO

- package-lock.json
- package.json
- Fix preview workflow not working.
> fix: preview workflow not working
